server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/employee_mgmt
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

keycloak:
  realm: new_realm
  auth-server-url: http://localhost:8088
  resource: employee-mgmt
  public-client: true
  bearer-only: true

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8088/realms/new_realm
